version: '3.8'

volumes:
  grafana_data: {}
  prometheus_data: {}

services:
  pushgateway:
    image: prom/pushgateway:latest
    restart: unless-stopped
    ports:
      - ${PUSH_PORT:-9091}:9091
    expose:
      - 9091

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    user: root
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PROM_DATA:-prometheus_data}:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - ${PROM_PORT:-9090}:9090
    expose:
      - 9090

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "472"
    depends_on:
      - prometheus
    ports:
      - ${GRAFANA_PORT:-3000}:3000
    expose:
      - 3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./dashboards:/etc/dashboards
    environment:
      - GF_AUTH_LOGIN_COOKIE_NAME=${NAME:-local}-grafana

  pushgateway-cleaner:
    image: onuryilmaz/prometheus-pushgateway-cleaner
    restart: unless-stopped
    command:
      - '-address=http://pushgateway:9091'
      - '-ttl=0h0m10s'
      - '-debug=true'
