version: '3.8'

volumes:
  grafana_data: {}
  prometheus_data: {}

services:
  pushgateway:
    image: prom/pushgateway:latest
    restart: unless-stopped
    expose:
      - 9091
    ports:
      - ${PUSH_PORT:-9091}:9091

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "472"
    depends_on:
      - prometheus
    ports:
      - ${GRAFANA_PORT:-3000}:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_AUTH_LOGIN_COOKIE_NAME=${NAME}-grafana
